language: ruby
sudo: required
rvm:
  - ruby-2.6.3
branches:
  only:
    - master
env:
  - REDMINE_VERSION=4.1.1 VERBOSE=yes
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - bash install-postgres-10.sh
script:
  - export PLUGIN=redmine_equality_plan
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
