language: ruby
dist: trusty
rvm:
  - ruby-2.6.3
branches:
  only:
    - master
services:
  - postgresql
addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  - REDMINE_VERSION=4.1.1 VERBOSE=yes
before_script:
  - psql -c 'create database redmine_test;' -U postgres
script:
  - export PLUGIN=redmine_equality_plan
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
