language: ruby
dist: trusty
rvm:
  - ruby-2.6.3
branches:
  only:
    - master
addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  - REDMINE_VERSION=4.1.1 VERBOSE=yes
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
before_script:
  - psql -c 'create database redmine_test;' -U postgres
script:
  - export PLUGIN=redmine_equality_plan
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
